apiVersion: apps/v1
kind: Deployment
metadata:
  name: soat-backend
  namespace: soat
  labels:
    app: soat-backend
    tier: backend
  annotations:
    maintainer: "SOAT - Grupo 75"
    description: "Deployment do backend da aplicação Java"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: soat-backend
  template:
    metadata:
      labels:
        app: soat-backend
    spec:
      containers:
        - name: soat-backend
          image: soat:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          envFrom:
            - configMapRef:
                name: soat-backend-config
            - secretRef:
                name: soat-backend-secret
          startupProbe:
            httpGet:
              path: /health
              port: 8080
            failureThreshold: 60
            timeoutSeconds: 5
            periodSeconds: 5
            initialDelaySeconds: 30
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
