# HPA desabilitado - réplicas fixadas em 1 no Deployment
# apiVersion: autoscaling/v2
# kind: HorizontalPodAutoscaler
# metadata:
#   name: soat-backend-hpa
#   namespace: soat
#   labels:
#     app: soat-backend
#     tier: autoscaler
#   annotations:
#     maintainer: "SOAT - Grupo 75"
#     description: "HPA fixado em 1 réplica (sem autoescalonamento)"
# spec:
#   scaleTargetRef:
#     apiVersion: apps/v1
#     kind: Deployment
#     name: soat-backend
#   minReplicas: 1
#   maxReplicas: 1
#   metrics:
#     - type: Resource
#       resource:
#         name: cpu
#         target:
#           type: Utilization
#           averageUtilization: 75
#   behavior:
#     scaleUp:
#       stabilizationWindowSeconds: 60
#       policies:
#         - type: Pods
#           value: 1
#           periodSeconds: 15
#     scaleDown:
#       stabilizationWindowSeconds: 60
#       policies:
#         - type: Pods
#           value: 1
#           periodSeconds: 30
