apiVersion: apps/v1
kind: Deployment
metadata:
  name: soat-backend
  namespace: soat
  labels:
    app: soat-backend
    tier: backend
  annotations:
    maintainer: "SOAT - Grupo 75"
    description: "Deployment do backend com réplicas fixas (HPA desativado)"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: soat-backend
  template:
    metadata:
      labels:
        app: soat-backend
    spec:
      containers:
        - name: soat-backend
          image: your-docker-registry/soat-backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 1Gi
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 3
      restartPolicy: Always
