services:
#  soat-backend:
#    container_name: soat-backend
#    build:
#      context: .
#      dockerfile: Dockerfile
#    image: soat:latest
#    environment:
#      DB_URL: jdbc:postgresql://soat-postgres:5432/soat
#      DB_USER: ${DB_USER}
#      DB_PASS: ${DB_PASS}
#    depends_on:
#      soat-postgres:
#        condition: service_healthy
#    networks:
#      - soat-network
#    ports:
#      - "8080:8080"
#    restart: always
#    healthcheck:
#      test: [ "CMD", "curl", "-f", "http://localhost:8080/health" ]
#      interval: 30s
#      timeout: 10s
#      retries: 3
#      start_period: 40s?

  soat-postgres:
    image: postgres:17
    container_name: soat-postgres
    environment:
      - POSTGRES_DB=soat
      - POSTGRES_USER=${DB_USER:-admin}
      - POSTGRES_PASSWORD=${DB_PASS:-123456}
    ports:
      - "5432:5432"
    networks:
      - soat-network
    volumes:
      - soat-postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER:-admin} -d soat" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

networks:
  soat-network:
    driver: bridge
    name: soat-network

volumes:
  soat-postgres-data:
    name: soat-postgres-data