server:
  servlet:
    context-path: /api
spring:
  application:
    name: soat
  docker:
    compose:
      enabled: false
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/soat}
    username: ${DB_USER:admin}
    password: ${DB_PASSWORD:123456}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: ${DB_SHOW_SQL:true}
springdoc:
  swagger-ui:
    path: /docs
management:
  endpoints:
    web:
      base-path: /